version: 2.1

commands:
  print_pipeline_id:
    description: "This is a re-usable command"
    parameters:
      to:
        type: string
        default: "circle_Workflow_ID"
    steps:
      - checkout
      - run: echo ${CIRCLE_WORKFLOW_ID} << parameters.to >>

  destroy_environment:
    description: "This is a re-usable command to destroy production environment when a job fails"
    parameters:
      to:
        type: string
        default: "environment is destoryed"
    steps:
      - checkout
      - run:
          name: destory environment
          command: |
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID}

orbs:
  welcome: circleci/aws-cli@2.0.3

jobs:
  run_step_on_fail:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            echo "This job will fail because the specified file path does not exit" > /failed_job/fail.txt
      - run:
          name: print fail job
          command: |
            echo "Hello, this job failed!"
          when: on_fail

  circle_Workflow_ID:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - print_pipeline_id

  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: |
            aws cloudformation deploy \
            --template-file template.yml \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID} \
            --region us-east-1

  configure_infrastructure:
    docker:
      - image: python:3.9.16-alpine3.17
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["15:71:24:06:04:09:fb:98:a5:85:17:31:e3:40:8b:03"]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main.yml

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: apk add --update curl
      - run:
          name: run smoke test
          command: |
            URL="https://blog.udacity.com/"
            if curl -s --head ${URL}
            then
              return 0
            else
              return 1
            fi

  roll_back:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: stimulate error # cause the job to fail
          command: |
            return 1
      - destroy_environment
    # when: on_fail

  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: Execute bucket.yml - Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
            --template-file cloudfront/bucket.yml \
            --stack-name stack-create-bucket-${CIRCLE_WORKFLOW_ID} \
            --parameter-overrides MyBucketName="mybucket-${CIRCLE_WORKFLOW_ID}"

  get_last_deployment_id:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Fetch and save the old pipeline ID (bucket name) responsible for the last release.
          command: |
            aws cloudformation \
            list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
            --no-paginate --output text > ~/textfile.txt

      - persist_to_workspace:
          root: ~/
          paths:
            - textfile.txt

  # Executes the cloudfront.yml template that will modify the existing CloudFront Distribution, change its target from the old bucket to the new bucket - `mybucket-${CIRCLE_WORKFLOW_ID:0:7}`.
  # Notice here we use the stack name `production-distro` which is the same name we used while deploying to the S3 bucket manually.
  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Execute cloudfront.yml
          command: |
            aws cloudformation deploy \
            --template-file cloudfront/cloudfront.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID="my-circle-bucket-${CIRCLE_WORKFLOW_ID}"

  clean_up_old_front_end:
    docker:
      - image: amazon/aws-cli
    attach_workspace:
      at: ~/
    steps:
      - checkout
      - run:
          name: Install tar utility
          command: |
            yum install -y tar gzip
      - run:
          name: Destroy the previous S3 bucket and CloudFormation stack.
          # Use $OldBucketID environment variable or mybucket644752792305 below.
          # Similarly, you can create and use $OldStackID environment variable in place of production-distro
          command: |
            export OldBucketID=$(cat ~/textfile.txt)
            aws s3 rm "s3://my-circle-bucket" --recursive

  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello"

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say world"
          command: "echo World!"

  print_env_name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo ${MY_ENV_NAME}

  save_print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: mkdir -p ~/workspace
      - run:
          command: |
            echo "say hello!" > ~/workspace/hello-output.txt
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - hello-output.txt

  print_hello_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run: |
          cat ~/workspace/hello-output.txt

  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: buld the node application
          command: |
            npm i
            npm run lint

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: test the node application
          command: |
            npm i
            npm run test

  analyse:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: analyse the node application
          command: |
            npm audit

workflows:
  hello-workflow:
    jobs:
      # - run_step_on_fail
      # - circle_Workflow_ID:
      #     requires:
      #       - run_step_on_fail
      # - create_infrastructure:
      #     requires:
      #       - circle_Workflow_ID
      # - configure_infrastructure:
      #     requires:
      #       - create_infrastructure
      # - smoke_test:
      #     requires:
      #       - configure_infrastructure
      # - roll_back:
      #     requires:
      #       - smoke_test
      - create_and_deploy_front_end
      - promote_to_production:
          requires:
            - create_and_deploy_front_end
      - get_last_deployment_id
      - clean_up_old_front_end:
          requires:
            - get_last_deployment_id
            - promote_to_production
