global:
  scrape_interval: 15s
  external_labels:
    monitor: "prometheus"

scrape_configs:
  - job_name: "node_exporter"

    static_configs:
      - targets: ["ec2-44-212-72-207.compute-1.amazonaws.com:9100"]
